from os import environ, path
CGAL_DIR = environ['CGAL_DIR']
BOOST_LIB_DIR = environ['BOOST_LIB_DIR']
BOOST_INCLUDE_DIR = environ['BOOST_INCLUDE_DIR']

env = Environment(TARGET_ARCH = ARGUMENTS.get('arch', None))

source = ['CGALTetrahedralize.cpp']

libpath = [
    path.join(CGAL_DIR,'lib'),
    path.join(CGAL_DIR,'auxiliary', 'gmp', 'lib'),
    BOOST_LIB_DIR
  ]
includepath = [
    path.join(CGAL_DIR,'include'),
    path.join(CGAL_DIR,'auxiliary', 'gmp', 'include'),
    BOOST_INCLUDE_DIR
]

libs = ['libgmp-10', 'libmpfr-4']

env.SharedLibrary('CGALTetrahedralize',source,
    CXXFLAGS='/EHsc /O2 /GS /GL /MD', 
    # /W3 /Gy /Zc:wchar_t /Zi /Gm- /O2 /sdl /fp:precise /D "WIN32" /D "NDEBUG" /D "_CONSOLE" /D "_LIB" /D "_WINDLL" /D "_UNICODE" /D "UNICODE" /D "_CRT_SECURE_NO_WARNINGS" /WX- /Zc:forScope /Gd /Oi /MD /EHsc /nologo',
    LINKFLAGS='/LTCG',
    LIBS=libs,CPPPATH=includepath,LIBPATH=libpath)
